name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Secrets
        id: modrinthtoken
        run:
          if: echo "Modrinth Api Token available? = " | echo secrets.MODRINTH_API != ''