name: Build and Publish Mod

on:
  workflow_dispatch:

concurrency:
  group: publish-mod
  cancel-in-progress: false

env:
  JAVA_VERSION: 25

jobs:
  # Test if everything compiles without any issue
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Compile Java
        run: gradle compileJava --no-daemon

  # Run the fabric
  gametests:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Run Fabric Gametests
        run: gradle :fabric:runGameTest
      - name: Run Forge Gametests
        run: gradle :forge:runGameTestServer
      - name: Run Neoforge Gametests
        run: gradle :neoforge:runGameTestServer

#  forge_gametest:
#    needs: compile_test
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout sources
#        uses: actions/checkout@v7
#      - name: Setup Java
#        uses: actions/setup-java@v5
#        with:
#          distribution: temurin
#          java-version: ${{ env.JAVA_VERSION }}
#      - name: Setup Gradle
#        uses: gradle/actions/setup-gradle@v6
#
#
#  neoforge_gametest:
#    needs: compile_test
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout sources
#        uses: actions/checkout@v7
#      - name: Setup Java
#        uses: actions/setup-java@v5
#        with:
#          distribution: temurin
#          java-version: ${{ env.JAVA_VERSION }}
#      - name: Setup Gradle
#        uses: gradle/actions/setup-gradle@v6
#      - name: Run Neoforge Gametests
#        run: gradle :neoforge:runGameTestServer