name: Build and Publish Mod

on:
  workflow_dispatch:

concurrency:
  group: publish-mod
  cancel-in-progress: false

env:
  ENVIRONMENT: client | server
  FABRIC_DEPENDENCIES: |
    fabric-api(required)
    mod-menu(optional)
  FORGE_DEPENDENCIES: |
  PUBLISH_MAVEN: false
  MAVEN_URL: "https://maven.sbvl.de/releases"
  MAVEN_USERNAME: ${{ secrets.MAVEN_USER }}
  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

jobs:
  # Read Mod properties and safe them in
  read_properties:
    runs-on: ubuntu-latest
    outputs:
          java_version: ${{ steps.props.outputs.java_version }}
          modrinth_id: ${{ steps.props.outputs.modrinth_id }}
          curseforge_id: ${{ steps.props.outputs.curseforge_id }}
          minecraft_version: ${{ steps.props.outputs.minecraft_version }}
          mod_version: ${{ steps.props.outputs.mod_version }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
      - name: Read Properties from gradle.properties
        id: props
        run: |
          # Base variables
          echo "java_version=$(grep '^java_version=' ./gradle.properties | cut -d'=' -f2)" >> "$GITHUB_OUTPUT"
          echo "modrinth_id=$(grep '^modrinth_id=' ./gradle.properties | cut -d'=' -f2)" >> "$GITHUB_OUTPUT"
          echo "curseforge_id=$(grep '^curseforge_id=' ./gradle.properties | cut -d'=' -f2)" >> "$GITHUB_OUTPUT"
          echo "minecraft_version=$(grep '^minecraft_version=' ./gradle.properties | cut -d'=' -f2)" >> "$GITHUB_OUTPUT"
          # Mod related
          echo "mod_version=$(grep '^version=' ./gradle.properties | cut -d'=' -f2)" >> "$GITHUB_OUTPUT"

  # 1. Test if the Code compiles successfully
  # 2. Run all Gametests for each loader
  # 3. Build the jar files if all tests are successfully
  # 4. Upload the Jar artifacts for publish
  test_and_build:
    runs-on: ubuntu-latest
    needs: read_properties
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v7
      - name: Setup Java Environment
        uses: actions/setup-java@v5
        with:
          java-version: ${{ needs.read_properties.outputs.java_version }}
          distribution: temurin
      - name: Setup Gradle Environment
        uses: gradle/actions/setup-gradle@v6
        # 1. Test if the Code compiles successfully
      - name: Test Compile all Projects
        run: gradle compileJava --no-daemon
        # 2. Run all Gametests for each loader
      - name: Run Fabric Gametests
        run: gradle :fabric:runGameTest
      - name: Run Forge Gametests
        run: gradle :forge:runGameTestServer
      - name: Run Neoforge Gametests
        run: gradle :neoforge:runGameTestServer
        # 3. Build the jar files if all tests are successfully
      - name: Build Mod Jars
        run: gradle build
        # 4. Upload the Jar artifacts for publish
      - name: Upload Build-Libs
        uses: actions/upload-artifact@v7
        with:
          name: build-libs
          path: |
            common/build/libs/*.jar
            fabric/build/libs/*.jar
            forge/build/libs/*.jar
            neoforge/build/libs/*.jar
          if-no-files-found: error


  # Now we upload the files to Curseforge and Modrinth
  mod_publish:
    needs: [read_properties, test_and_build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: build-libs
      # Fabric
      - name: Publish Fabric build
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ needs.read_properties.outputs.modrinth_id }}
          modrinth-token: ${{ secrets.MODRINTH_API }}
          curseforge-id: ${{ needs.read_properties.outputs.curseforge_id }}
          curseforge-token: ${{ secrets.CURSEFORGE_API }}
          files: fabric/build/libs/!(*-@(dev|sources|javadoc)).jar
          version: "${{ needs.read_properties.outputs.minecraft_version }}-${{ needs.read_properties.outputs.mod_version }}"
          version-type: release
          changelog-file: 'CHANGELOG.md'
          loaders: fabric, quilt
          game-versions: ${{ needs.read_properties.outputs.minecraft_version }}
          java: ${{ needs.read_properties.outputs.java_version }}
          dependencies: ${{ env.FABRIC_DEPENDENCIES }}
          environment: ${{ env.ENVIRONMENT }}
          retry-attempts: 2
          retry-delay: 10000
      # Forge
      - name: Publish Forge build
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ needs.read_properties.outputs.modrinth_id }}
          modrinth-token: ${{ secrets.MODRINTH_API }}
          curseforge-id: ${{ needs.read_properties.outputs.curseforge_id }}
          curseforge-token: ${{ secrets.CURSEFORGE_API }}
          files: forge/build/libs/!(*-@(dev|sources|javadoc)).jar
          version: "${{ needs.read_properties.outputs.minecraft_version }}-${{ needs.read_properties.outputs.mod_version }}"
          version-type: release
          changelog-file: 'CHANGELOG.md'
          loaders: forge
          game-versions: ${{ needs.read_properties.outputs.minecraft_version }}
          java: ${{ needs.read_properties.outputs.java_version }}
          dependencies: ${{ env.FORGE_DEPENDENCIES }}
          environment: ${{ env.ENVIRONMENT }}
          retry-attempts: 2
          retry-delay: 10000
      # Neoforge
      - name: Publish Neoforge build
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ needs.read_properties.outputs.modrinth_id }}
          modrinth-token: ${{ secrets.MODRINTH_API }}
          curseforge-id: ${{ needs.read_properties.outputs.curseforge_id }}
          curseforge-token: ${{ secrets.CURSEFORGE_API }}
          files: neoforge/build/libs/!(*-@(dev|sources|javadoc)).jar
          version: "${{ needs.read_properties.outputs.minecraft_version }}-${{ needs.read_properties.outputs.mod_version }}"
          version-type: release
          changelog-file: 'CHANGELOG.md'
          loaders: neoforge
          game-versions: ${{ needs.read_properties.outputs.minecraft_version }}
          java: ${{ needs.read_properties.outputs.java_version }}
          dependencies: ${{ env.FORGE_DEPENDENCIES }}
          environment: ${{ env.ENVIRONMENT }}
          retry-attempts: 2
          retry-delay: 10000

  # Upload all jars to you maven but only if PUBLISH_MAVEN is true
  maven_publish:
    if: env.PUBLISH_MAVEN
    needs: [read_properties, test_and_build]
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v7
      - name: Setup Java Environment
        uses: actions/setup-java@v5
        with:
          java-version: ${{ needs.read_properties.outputs.java_version }}
          distribution: temurin
      - name: Setup Gradle Environment
        uses: gradle/actions/setup-gradle@v6
      - name: Publish Maven
        run: gradle publish --no-daemon